
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class HOME_PAGE extends javax.swing.JFrame {

    /**
     * Creates new form HOME_PAGE
     */
    public HOME_PAGE() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
public void close(){
    WindowEvent winclose=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JTextField jTextField1 = new javax.swing.JTextField();
        javax.swing.JButton btnstudent = new javax.swing.JButton();
        javax.swing.JButton btnstaff = new javax.swing.JButton();
        javax.swing.JButton btnhod = new javax.swing.JButton();
        javax.swing.JButton btnadmin = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 204, 204));
        jTextField1.setForeground(new java.awt.Color(153, 153, 0));
        jTextField1.setText("SELECT USER");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(6, 103, 130, 40);

        btnstudent.setBackground(new java.awt.Color(0, 255, 255));
        btnstudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnstudent.setForeground(new java.awt.Color(0, 204, 204));
        btnstudent.setText("STUDENT");
        btnstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnstudent);
        btnstudent.setBounds(18, 205, 91, 35);

        btnstaff.setBackground(new java.awt.Color(102, 255, 255));
        btnstaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnstaff.setForeground(new java.awt.Color(0, 204, 204));
        btnstaff.setText("STAFF");
        btnstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstaffActionPerformed(evt);
            }
        });
        jPanel1.add(btnstaff);
        btnstaff.setBounds(18, 290, 91, 33);

        btnhod.setBackground(new java.awt.Color(51, 255, 255));
        btnhod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnhod.setForeground(new java.awt.Color(0, 204, 204));
        btnhod.setText("HOD");
        btnhod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhodActionPerformed(evt);
            }
        });
        jPanel1.add(btnhod);
        btnhod.setBounds(18, 374, 91, 33);

        btnadmin.setBackground(new java.awt.Color(51, 255, 255));
        btnadmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnadmin.setForeground(new java.awt.Color(0, 204, 204));
        btnadmin.setText("ADMIN");
        btnadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminActionPerformed(evt);
            }
        });
        jPanel1.add(btnadmin);
        btnadmin.setBounds(18, 454, 91, 33);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("                                                   HELLO,WELCOME TO KISII UNIVERSITY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 14, 795, 57);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Desktop\\aaaksupics\\ksu1(1)(1).png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 60, 1080, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudentActionPerformed
        // TODO add your handling code here:
      setVisible(false);
        STUDENT_LOGIN lg=new STUDENT_LOGIN();
        lg.setVisible(true);
       
    }//GEN-LAST:event_btnstudentActionPerformed

    private void btnstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstaffActionPerformed
        // TODO add your handling code here:
         setVisible(false);
         STAFF_LOGIN st=new STAFF_LOGIN();
        st.setVisible(true);
    }//GEN-LAST:event_btnstaffActionPerformed

    private void btnhodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhodActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        HOD_LOGIN hd=new  HOD_LOGIN();
        hd.setVisible(true);
    }//GEN-LAST:event_btnhodActionPerformed

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        ADMIN_LOGIN ad=new ADMIN_LOGIN();
        ad.setVisible(true);
    }//GEN-LAST:event_btnadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME_PAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
